# Generated by Django 5.0.6 on 2024-07-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'OK'), (4, 'Good'), (5, 'Excellent')]),
        ),
    ]
